<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[STEP1]]>
    </line>
    <line>
      <![CDATA[STEP2]]>
    </line>
    <line>
      <![CDATA[STEP3]]>
    </line>
  </reporter-output>
  <suite name="Fipsar QA" duration-ms="136238" started-at="2018-03-09T19:49:41Z" finished-at="2018-03-09T19:51:58Z">
    <groups>
    </groups>
    <test name="Fipsar" duration-ms="136238" started-at="2018-03-09T19:49:41Z" finished-at="2018-03-09T19:51:58Z">
      <class name="TestNGClass">
        <test-method status="PASS" signature="testCaseProvider()[pri:0, instance:TestNGClass@4d95d2a2]" name="testCaseProvider" is-config="true" duration-ms="607" started-at="2018-03-10T01:19:41Z" finished-at="2018-03-10T01:19:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseProvider -->
        <test-method status="FAIL" signature="launchapp(com.fipsar.qa.utils.TestParameters)[pri:0, instance:TestNGClass@4d95d2a2]" name="launchapp" duration-ms="135572" started-at="2018-03-10T01:19:42Z" data-provider="data" finished-at="2018-03-10T01:21:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Patient_Login_Validation_chrome]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.fipsar.qa.commands.Manipulation.verifyElementIsPresent(Manipulation.java:592)
	at com.fipsar.qa.util.CommandUtils.executeAction(CommandUtils.java:427)
	at com.fipsar.qa.datadriver.TestCaseRunner.exectuteTestCase(TestCaseRunner.java:79)
	at TestNGClass.launchapp(TestNGClass.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[STEP1]]>
            </line>
            <line>
              <![CDATA[STEP2]]>
            </line>
            <line>
              <![CDATA[STEP3]]>
            </line>
          </reporter-output>
        </test-method> <!-- launchapp -->
      </class> <!-- TestNGClass -->
    </test> <!-- Fipsar -->
  </suite> <!-- Fipsar QA -->
</testng-results>
