<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-TBBKICN8" name="TestNGClass" tests="1" failures="0" timestamp="09 Mar 2018 19:51:58 GMT" time="135.572" errors="1">
  <testcase name="launchapp" time="135.572" classname="TestNGClass">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.fipsar.qa.commands.Manipulation.verifyElementIsPresent(Manipulation.java:592)
	at com.fipsar.qa.util.CommandUtils.executeAction(CommandUtils.java:427)
	at com.fipsar.qa.datadriver.TestCaseRunner.exectuteTestCase(TestCaseRunner.java:79)
	at TestNGClass.launchapp(TestNGClass.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- launchapp -->
</testsuite> <!-- TestNGClass -->
